"""
Django settings for mon_ecommerce project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import os

os.environ['PG_OPTIONS'] = '-c client_min_messages=notice -c lc_messages=en_US.UTF-8'

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-h7txffe622dq_tw8oqd0dqa==fmgwub7#qwav@9ot7i+&)m#@7'

DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    # Applications Django natives
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Requis par django-allauth
    
    # Vos applications e-commerce locales
    'utilisateurs',
    'catalogue',
    'commandes',
    'panier',
    'paiements',
    'avis',
    'debug_toolbar',
    
    # Packages tiers (Authentification Sociale)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Requis par allauth
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'mon_ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # Requis par allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mon_ecommerce.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'vente_ligne_db',         
        'USER': 'postgres',           
        'PASSWORD': '1234',   
        'HOST': '127.0.0.1',           
        'PORT': '5432', 
        'OPTIONS': {
            'options': '-c client_min_messages=notice -c lc_messages=en_US.UTF-8'
        },                  
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'  # Changé en français pour votre e-commerce

TIME_ZONE = 'Europe/Paris'  # Ajustez selon votre zone horaire

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
SESSION_SAVE_EVERY_REQUEST = True


# --- CONFIGURATION PERSONNALISÉE DU PROJET ---

# Modèle utilisateur personnalisé
AUTH_USER_MODEL = 'utilisateurs.Utilisateur'

# Configuration globale de Django-Allauth
LOGIN_REDIRECT_URL = '/'  
LOGOUT_REDIRECT_URL = '/' 
ACCOUNT_LOGOUT_REDIRECT_URL = '/compte/connexion/'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'optional' 
SOCIALACCOUNT_LOGIN_ON_GET = True

# Configuration des API fournisseurs (Remplacer par vos vraies clés en temps voulu)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': 'votre-client-id-google.apps.googleusercontent.com',
            'secret': 'votre-cle-secrete-google',
            'key': ''
        }
    },
    'facebook': {
        'APP': {
            'client_id': 'votre-client-id-facebook',
            'secret': 'votre-cle-secrete-facebook',
            'key': ''
        }
    }
}
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')